# Generated by Django 4.0.1 on 2022-05-17 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('charge_type', models.CharField(choices=[('P', 'Percentage'), ('F', 'Fixed')], max_length=1)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('issued_on', models.DateField()),
                ('due_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_invoices', to=settings.AUTH_USER_MODEL)),
                ('discounts', models.ManyToManyField(blank=True, related_name='invoices', to='invoices.Discount')),
                ('invoicer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cost', models.FloatField()),
                ('sku', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('charge_type', models.CharField(choices=[('P', 'Percentage'), ('F', 'Fixed')], max_length=1)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tax_type', models.CharField(choices=[('GST', 'General Sales Tax'), ('HST', 'Harmonized Sales Tax'), ('PST', 'Provincial Sales Tax'), ('QST', 'Quebec Sales Tax')], max_length=3)),
                ('name', models.CharField(max_length=16)),
                ('percentage', models.FloatField()),
                ('identifier', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('quantity', models.FloatField()),
                ('notes', models.CharField(blank=True, default='', max_length=256)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.product')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file', models.FileField(upload_to='')),
                ('file_type', models.CharField(choices=[('P', 'PDF'), ('T', 'TXT'), ('C', 'CSV'), ('H', 'HTML')], editable=False, max_length=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='surcharges',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='invoices.Surcharge'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='invoices.Tax'),
        ),
    ]
