# Generated by Django 4.0.1 on 2022-05-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('S', 'Sent'), ('R', 'Received'), ('D', 'Due'), ('L', 'Late'), ('P', 'Payed')], max_length=1),
        ),
    ]
