# Generated by Django 4.0.4 on 2022-05-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('apt_type', models.CharField(blank=True, choices=[('U', 'Unit'), ('S', 'Suite'), ('A', 'Apt'), ('R', 'Room')], max_length=1, null=True)),
                ('apt', models.IntegerField(blank=True, null=True)),
                ('postal', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('discount_type', models.CharField(choices=[('P', 'Percentage'), ('F', 'Fixed')], max_length=1)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField()),
                ('due_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.client')),
                ('discounts', models.ManyToManyField(related_name='invoices', to='core.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('sku', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('note', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('GST', 'General Sales Tax'), ('HST', 'Harmonized Sales Tax'), ('PST', 'Provincial Sales Tax'), ('QST', 'Quebec Sales Tax')], max_length=3)),
                ('name', models.CharField(max_length=16)),
                ('percentage', models.FloatField()),
                ('identifier', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=4)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalities', to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='Invoicer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('sku', models.CharField(max_length=8)),
                ('cost', models.FloatField()),
                ('quantity', models.FloatField()),
                ('total', models.FloatField()),
                ('notes', models.CharField(blank=True, default='', max_length=256)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=10485760, upload_to='')),
                ('file_type', models.CharField(choices=[('P', 'PDF'), ('T', 'TXT'), ('C', 'CSV'), ('H', 'HTML')], editable=False, max_length=1)),
                ('invoice', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoicer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.invoicer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxes',
            field=models.ManyToManyField(related_name='invoices', to='core.tax'),
        ),
        migrations.AddField(
            model_name='address',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='core.municipality'),
        ),
    ]
