# Generated by Django 4.0.1 on 2022-05-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicefile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
