# Generated by Django 4.0.4 on 2022-05-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_invoice_issued_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.tax'),
        ),
    ]
