# Generated by Django 4.0.1 on 2022-05-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_emailattempt_invoice'),
        ('core', '0003_alter_invoicefile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoicer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='surcharges',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='invoicefile',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceFile',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Surcharge',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
