# Generated by Django 4.0.4 on 2022-04-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalities', to='core.region')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='municipality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='core.municipality'),
            preserve_default=False,
        ),
    ]
