# Generated by Django 4.0.1 on 2022-05-07 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_discount_id_alter_invoice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=32)),
                ('charge_type', models.CharField(choices=[('P', 'Percentage'), ('F', 'Fixed')], max_length=1)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='discount_type',
            new_name='charge_type',
        ),
    ]
