# Generated by Django 4.0.4 on 2022-05-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_invoice_discounts_alter_invoice_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
