# Generated by Django 4.0.1 on 2022-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_surcharge_rename_discount_type_discount_charge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='surcharges',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.Surcharge'),
        ),
    ]
