# Generated by Django 4.0.4 on 2022-04-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_address_country_remove_address_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
    ]
