# Generated by Django 4.0.4 on 2022-05-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
