# Generated by Django 4.0.4 on 2022-04-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.client'),
            preserve_default=False,
        ),
    ]
