# Generated by Django 4.0.1 on 2022-05-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.Discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.Tax'),
        ),
    ]
