# Generated by Django 4.0.4 on 2022-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
