# Generated by Django 4.0.4 on 2022-04-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_address_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
