# Generated by Django 4.0.4 on 2022-04-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_address_apt_alter_address_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apt_type',
            field=models.CharField(blank=True, choices=[('U', 'Unit'), ('S', 'Suite'), ('A', 'Apt')], max_length=1, null=True),
        ),
    ]
