# Generated by Django 4.0.4 on 2022-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_address_apt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
