# Generated by Django 4.0.4 on 2022-04-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invoiceitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
