# Generated by Django 4.0.1 on 2022-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattempt',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('S', 'Success'), ('F', 'Failure')], default='C', max_length=1),
        ),
    ]
