# Generated by Django 4.0.1 on 2022-05-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('notifications', '0002_emailattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattempt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_attempts', to='invoices.invoice'),
        ),
    ]
