# Generated by Django 4.0.1 on 2022-05-07 01:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helcimcredittransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='helcimdebittransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
